table df_paciente_dia
	lineageTag: 75662435-da8a-4dd1-8368-74a1253c2b1f

	column FECHA
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0aba945-4753-4dca-82fa-6aba09cffe47
		summarizeBy: none
		sourceColumn: FECHA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ESTACION
		dataType: string
		lineageTag: a7b31b0e-9081-4357-96ca-71060fc996ed
		summarizeBy: none
		sourceColumn: ESTACION

		annotation SummarizationSetBy = Automatic

	column PACIENTEDIA
		dataType: int64
		formatString: 0
		lineageTag: 32db305b-68f2-4669-9c92-9766ba9d2451
		summarizeBy: sum
		sourceColumn: PACIENTEDIA

		annotation SummarizationSetBy = Automatic

	partition df_paciente_dia = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("Z:\JEFATURA\POWER BI GENERAL\HOSPITALIZACION\bases\indicador\df_paciente_dia.csv"), [Delimiter = ",", Columns = 3, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"FECHA", type date}, {"ESTACION", type text}, {"PACIENTEDIA", Int64.Type}}, "es")
				in
				  #"Tipo de columna cambiado"

	annotation PBI_ResultType = Table

